name: PostAir API Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run PostAir test suite
        run: postman collection run <collectionId> -e <enviromentId>
