name: PostAir API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository files
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh

      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Airports data-driven tests
        run: postman collection run 34564324-5b292217-008c-4b9f-bd30-f69360e4fea1 -e 34564324-4102ebb0-717e-4317-bd2a-4d382b940a14 -i Airports -d "Pruebas.csv"
